app_identifier "com.latest.first" # The bundle identifier of your app
username "krish@seattleapplab.com" # your Apple ID user


name(
  'en-US' => "LatestFirst app by jaljale"
)
description({
  'en-US' => "<app_description>",
})
release_notes(
  'en-US' => '<app_release_notes>'
)
keywords(
  'en-US' => '<app_keywords>'
)
privacy_url(
  'en-US' => '<app_privacy_url>'
)
marketing_url(
  'en-US' => '<app_marketing_url>'
)
support_url(
  'en-US' => '<app_support_url>'
)

app_icon "fastlane/icon_ios.png"

copyright "#{Time.now.year} <company>"

primary_category "<app_primary_category>"

secondary_category "<app_secondary_category>"

app_rating_config_path "fastlane/app_rating.json"

submit_for_review <submit_for_review>

automatic_release <automatic_release>

price_tier <price_tier>

app_review_information(
  first_name: "<first_name>",
  last_name: "<last_name>",
  phone_number: "<phone_number>",
  email_address: "<email_address>",
  demo_user: "<demo_user>",
  demo_password: "<demo_password>",
  notes: "<notes>"
)
